version: '3.8'

services:
        db:
                image: postgres:12.2
                volumes:
                        - ../postgresql_data:/var/lib/postgresql/data
                env_file:
                        - .env
                ports:
                        - 5432:5432
                user: "1000:1000"
